name: Test

on: [push, pull_request]

jobs:
  pytest-win:
    name: 'pytest ${{ matrix.platform.name }}'
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Windows', os: 'ubuntu-latest' }
          - { name: 'Linux',   os: 'windows-latest' }

    steps:
    - uses: actions/checkout@v4

    - name: Install python libraries
      shell: bash
      run: |
        pip install -r requirements.txt -r requirements-tests.txt

    - name: Run python unit tests (Windows)
      shell: bash
      run: |
        pytest .
